#pragma once

#define NUMBOARDS 1
#define ENCODER_NUM_ENCODERS NUMBOARDS * 8 + 1
#define ENCODER_POLL_INTERVAL_MS 2

#define BUTT_SHIFT_NUMBER_OF_SHIFT_REGISTER NUMBOARDS * 2
#define BUTT_SHIFT_NUMBER_OF_BUTTONS BUTT_SHIFT_NUMBER_OF_SHIFT_REGISTER * 8
#define BUTT_SHIFT_LOAD_PIN 8
#define BUTT_SHIFT_CLK_ENABLE_PIN 6
#define BUTT_SHIFT_DATA_PIN 5
#define BUTT_SHIFT_CLK_PIN 7
#define BUTT_SHIFT_POLL_INTERVAL_MS 5

#define DISPLAY_WIDTH 128
#define DISPLAY_HEIGHT 64
#define DISPLAY_RESET     -1
#define DISPLAY_ADDRESS 0x3C

#define LED_SHIFT_CLOCK_PIN 9
#define LED_SHIFT_LATCH_PIN 11
#define LED_SHIFT_DATA_PIN 12

#define I2C_SPEED 400000

// Need to clean up encoder section
const int NUM_ENCODERS = ENCODER_NUM_ENCODERS;